config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root to: 'welcome#index'
  
  get '/dashboard', to: 'dashboard#index' 
  get '/orders/:id', to: 'orders#new'
  post '/orders/create'
  get 'welcome/index'

  namespace :admin do 
    get '/dashboard', to: 'dashboard#index'
    get '/users', to: 'users#index'
    get '/items', to: 'items#index'
    get '/item/new', to: 'items#new'
    get '/orders/:id', to: 'orders#show'
    post '/item/create', to: 'items#create'
  end

  namespace :api do 
    namespace :v1 do 
      resources :orders
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user

  validates :first_id, :main_id, :drink_id, presence: true

  attr_accessor :items

  def load_items
    if @items.nil?
      @items = []
      @items << Menu.find(first_id)
      @items << Menu.find(main_id)
      @items << Menu.find(drink_id)
    end
  end

  def get_total_cost
    cost = 0
    @items.each do |item|
      cost += item.price
    end
    cost
  end

  def self.total_orders_cost(orders)
    cost = 0
    orders.each do |order|
      order.load_items
      cost += order.get_total_cost
    end
    cost
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::AdminBaseController
  def show
    date = get_date_for_current_wday(params[:id].to_i)
    @orders = get_record_by_date(date, Order)
  end
end

app/controllers/api/v1/orders_controller.rb
class Api::V1::OrdersController < ApplicationController 
  before_action :doorkeeper_authorize!
  respond_to :json

  def index
    @order = get_record_by_date(Date.today, Order)
    respond_with @order
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    date = get_date_for_current_wday(params[:id].to_i)
    @menu = get_record_by_date(date, Menu)

    @meals = Array.new
    @menu.each do |m|
      @meals << m.meal_type.kind unless @meals.include? m.meal_type.kind
    end
  end

  def create
    params.permit(:first, :drink, :main)

    @order = Order.new()
    
    @order.first_id = params[:first]
    @order.main_id = params[:main]
    @order.drink_id = params[:drink]
    @order.user = current_user

    if @order.save
      flash[:notice] = "Order processed. Thank you!"
      redirect_to root_path
    else
      flash[:notice] = "Choose three dishes."
      redirect_to request.referrer
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  
end

app/views/orders/new.html.haml
- unless @menu.empty?
  = form_tag(orders_create_path, methos: 'post') do
    - @meals.each do |kind|
      .item{ :id => "item-#{kind}" }
        - @menu.each do |meal|
          - if kind == meal.meal_type.kind
            .row
              .col-md-3
                - unless meal.image.url.nil?
                  = image_tag(meal.image.url, :class => 'img-thumbnail')
              .col-md-9
                #item-desc
                  = label_tag(:meal, "#{meal.name}")
                #item-desc
                  Price: 
                  = "#{meal.price} $"
                #item-desc
                  Add
                  = radio_button_tag(kind, meal.id)
                

    = submit_tag('Complete')
- else
  #empty-menu
    Menu is empty!