config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root to: 'welcome#index'
  
  get '/dashboard', to: 'dashboard#index' 
  get '/orders/:id', to: 'orders#new'
  post '/orders/create'
  get 'welcome/index'

  namespace :admin do 
    get '/dashboard', to: 'dashboard#index'
    get '/users', to: 'users#index'
    get '/items', to: 'items#index'
    get '/item/new', to: 'items#new'
    get '/orders/:id', to: 'orders#show'
    post '/item/create', to: 'items#create'
  end

  namespace :api do 
    namespace :v1 do 
      resources :orders
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meal_type.rb
class MealType < ApplicationRecord
  has_many :menus
end

app/models/menu.rb
class Menu < ApplicationRecord
  mount_uploader :image, ImageUploader

  belongs_to :meal_type
  validates :name, :price, :meal_type_id, presence: true
  validates :price, numericality: { only_integer: true }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user

  validates :first_id, :main_id, :drink_id, presence: true

  attr_accessor :items

  def load_items
    if @items.nil?
      @items = []
      @items << Menu.find(first_id)
      @items << Menu.find(main_id)
      @items << Menu.find(drink_id)
    end
  end

  def get_total_cost
    cost = 0
    @items.each do |item|
      cost += item.price
    end
    cost
  end

  def self.total_orders_cost(orders)
    cost = 0
    orders.each do |order|
      order.load_items
      cost += order.get_total_cost
    end
    cost
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :validatable

  def set_admin_first_user
    self.admin = true if User.first.id == self.id
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  def index
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < Admin::AdminBaseController
  def new
    @item = Menu.new
  end

  def create
    @item = Menu.new(menu_params)

    if @item.save
      flash[:notice] = "Item successfully added!"
      redirect_to action: "index"
    else
      render :new
    end
  end

  def index
    @items = get_record_by_date(Date.current, Menu)
  end

  protected

  def menu_params
    params.require(:menu).permit(:name, :price, :meal_type_id, :image)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::AdminBaseController
  def show
    date = get_date_for_current_wday(params[:id].to_i)
    @orders = get_record_by_date(date, Order)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminBaseController
  def index
    @users = User.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  protect_from_forgery with: :exception
  before_action :configure_permitted_paramters, if: :devise_controller?

  protected
    def configure_permitted_paramters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
        devise_parameter_sanitizer.permit(:account_update, keys: [:username])
    end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    date = get_date_for_current_wday(params[:id].to_i)
    @menu = get_record_by_date(date, Menu)

    @meals = Array.new
    @menu.each do |m|
      @meals << m.meal_type.kind unless @meals.include? m.meal_type.kind
    end
  end

  def create
    params.permit(:first, :drink, :main)

    @order = Order.new()
    
    @order.first_id = params[:first]
    @order.main_id = params[:main]
    @order.drink_id = params[:drink]
    @order.user = current_user

    if @order.save
      flash[:notice] = "Order processed. Thank you!"
      redirect_to root_path
    else
      flash[:notice] = "Choose three dishes."
      redirect_to request.referrer
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_record_by_date(date, model)
    model.where(:created_at => date.beginning_of_day..date.end_of_day)
  end

  def get_date_for_current_wday(wday)
    wday -= 1
    Date.today.at_beginning_of_week + wday.day
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/days/show.html.haml
= form_tag('/order', methos: 'post') do
  - @meals.each do |kind|
    %ul
      = kind
      - @menu.each do |meal|
        - if kind == meal.meal_type.kind
          %li
            = label_tag(:meal, "#{meal.name} - #{meal.price}$")
            = radio_button_tag(kind, meal.name)

  = submit_tag('Complete')

app/views/layouts/application.html.haml
%html
  %head
    %title LunchesApp
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    .container
      #nav
        %ul{:class => 'nav nav-pills'}
          %li.nav-item
            %li
              = link_to('Home', root_path, class: "nav-link")
          %li.nav-item
          - if user_signed_in?
            %li
              = link_to('Dashboard', dashboard_path, class: "nav-link")
            -if current_user.admin? 
              %li
                = link_to('Orders', admin_dashboard_path, class: "nav-link")
              %li
                = link_to('New item', admin_item_new_path, class: "nav-link")
            %li
              = link_to(current_user.username, edit_user_registration_path, class: "nav-link")
            %li
              = link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-link")
          - else
            %li
              = link_to('Login', new_user_session_path, class: "nav-link")

    .container
      #content
        %p.notice
          = notice
        %p.alert
          = alert
        = yield